   <table border="1" id="myTable">
    <tr>
	  <th><?=$this->translate->_('ID')?></th>
	  <th><?=$this->translate->_('User Name')?></th>	  
	  <th><?=$this->translate->_('First Name')?></th>	  
	  <th><?=$this->translate->_('Last Name')?></th>	  
	  <th><?=$this->translate->_('Status')?></th>	  
	  <th><?=$this->translate->_('Action')?></th>	  
	</tr>
  <? $datas = $this->datas;
     for($i = 0; $i< count($datas);$i++){ ?>
    <tr>
	  <td><?=$datas[$i]['id']?></td>	
	  <td><?=$datas[$i]['user_email_address']?></td>
	  <td><?=$datas[$i]['first_name']?></td>	  
	  <td><?=$datas[$i]['last_name']?></td>	  
	  <td><?=$datas[$i]['status']?></td>	  
	  <td><span id="status_<?=$datas[$i]['id']?>">
			<?if($datas[$i]['status']=='active'){?>
	    <a onclick="getContents('<?=$this->projectUrl?>admin/cinactive/id/<?=$datas[$i]['id']?>','status_<?=$datas[$i]['id']?>')"><?=$this->translate->_('Inactivate')?></a>
			<?}else{?>
	    <a onclick="getContents('<?=$this->projectUrl?>admin/cactive/id/<?=$datas[$i]['id']?>','status_<?=$datas[$i]['id']?>')"><?=$this->translate->_('Activate')?></a>
			<?}?></span>
		|
	    <a href="<?=$this->projectUrl?>user/edit/id/<?=$datas[$i]['id']?>"><?=$this->translate->_('Edit')?></a>
		|
	    <a onclick="return deleteClient(this);" id="del_<?=$datas[$i]['id']?>"><?=$this->translate->_('Delete')?></a>		
	  </td>	  
	</tr> 
  <? } ?>
  </table>
  <div  id="paginator" ><?=($this->display_page);?></div>
